name: Build

on:
  push:
    paths:
      - '*.md'
      - 'template.html'
      - '**/*.yml'

jobs:
  html:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    concurrency:
      group: ci
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v4

      - name: Install pandoc
        run: sudo apt-get install -y pandoc

      - name: Compile HTML with make/pandoc
        run: make build

      - name: Push latest HTML
        run: |
          git config --global user.email 'otp-bot@opentripplanner.org'
          git config --global user.name 'OTP Bot'
          git pull
          git add *.html
          git commit -m "Add compiled HTML" || true
          git push

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./"

  deploy:
    permissions:
      contents: read
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    needs: html
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    steps:
      - name: Deploy artifact
        id: deployment
        uses: actions/deploy-pages@v4
