name: Build

on:
  push:
    paths:
      - '*.md'
      - 'template.html'

jobs:
  html:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4

      - name: Install pandoc
        run: sudo apt-get install -y pandoc

      - name: Compile HTML with make/pandoc
        run: make build

      - name: Push latest HTML
        run: |
          sleep 45
          git config --global user.email 'otp-bot@opentripplanner.org'
          git config --global user.name 'OTP Bot'
          git add *.html
          git commit -m "Add compiled HTML"
          git push
          
